version: '3.1'

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres1'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'postgres1'
      POSTGRES_PORT: 5432